import {
  completeUploadJob,
  createUploadJob,
  getVideoJobById,
  isValidIsoDateTime,
  listUploadJobs,
} from '@trend-to-video-studio/core';
import { getUploadProvider, listUploadProviders } from '@trend-to-video-studio/providers';
import { NextRequest, NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    ok: true,
    items: listUploadJobs(),
    providers: listUploadProviders(),
  });
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  const videoJobId = String(body?.videoJobId ?? '');

  if (!videoJobId) {
    return NextResponse.json(
      {
        ok: false,
        error: 'videoJobId is required',
      },
      { status: 400 },
    );
  }

  const videoJob = getVideoJobById(videoJobId);
  if (!videoJob) {
    return NextResponse.json(
      {
        ok: false,
        error: 'videoJobId does not exist',
      },
      { status: 404 },
    );
  }

  if (!videoJob.outputUrl) {
    return NextResponse.json(
      {
        ok: false,
        error: 'videoJob must have outputUrl before upload',
      },
      { status: 400 },
    );
  }

  const scheduledFor = body?.scheduledFor
    ? String(body.scheduledFor)
    : new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();

  if (!isValidIsoDateTime(scheduledFor)) {
    return NextResponse.json(
      {
        ok: false,
        error: 'scheduledFor must be a valid ISO datetime string',
      },
      { status: 400 },
    );
  }

  const provider = getUploadProvider(String(body?.provider ?? '') || undefined);
  const created = createUploadJob(videoJobId, scheduledFor);
  const providerResult = await provider.uploadVideo({
    videoUrl: videoJob.outputUrl,
    title: String(body?.title ?? `Trend-to-Video Upload ${videoJob.id}`),
    description: String(body?.description ?? 'Generated by trend-to-video-studio'),
    scheduledFor,
  });
  const completed = completeUploadJob(created.id);

  return NextResponse.json({
    ok: true,
    item: completed,
    providerResult,
  });
}
